name: Run The Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  EMAIL: ${{ secrets.EMAIL }}
  SENHA: ${{ secrets.SENHA }}
  ARDOC: ${{ secrets.ARDOC }}

jobs:
  automation:
    runs-on: ubuntu-latest
    container: ghcr.io/prestessr/robot-image-prestes:latest
    steps:
      - uses: actions/checkout@v4
      - name: Automation
        run: xvfb-run --server-args="-screen 0 1366x768x24" robot --removekeywords NAME:\*Get\ Env\*  -d results tests

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: log
          path: results/
          retention-days: 2


      